version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:latest

    steps:
      - checkout
      - run: mvn dependency:go-offline
      - run: mvn clean package
      - run: mvn clean compile jib:build -Djib.to.auth.username=$DOCKER_USERNAME -Djib.to.auth.password=$DOCKER_PASS -Dimage=ismayilkarimli/wtw:$CIRCLE_BUILD_NUM


