version: 2.1

jobs:
  build:
    docker:
      - image:circleci/openjdk:11.0.1-jdk

    steps:
      - checkout
    - run: mvn dependency:go-offline
    - run: mvn clean package
    - run: mvn clean compile jib:build -Djib.to.auth.username=$DOCKER_USERNAME -Djib.to.auth.password=$DOCKER_PASS -Dimage=ismayilkarimli/as02:$CIRCLE_BUILD_NUM

    - store_artifacts:
        path: target/classes
        destination: as02

